// <auto-generated />
using EastviewRestAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EastviewRestAPI.Migrations
{
    [DbContext(typeof(EastviewDbContext))]
    partial class EastviewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EastviewRestAPI.Models.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Citizens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1512 Doe St",
                            FirstName = "John",
                            Job = "Constructor",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1512 Doe St",
                            FirstName = "Jane",
                            Job = "Actress",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            Address = "302 Peachtree St",
                            FirstName = "Steve",
                            Job = "Student",
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("EastviewRestAPI.Models.CitizenTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CitizenId = 1,
                            Day = 1,
                            Description = "Finish house kitchen"
                        },
                        new
                        {
                            Id = 2,
                            CitizenId = 2,
                            Day = 1,
                            Description = "Film TV Serie chapter"
                        },
                        new
                        {
                            Id = 3,
                            CitizenId = 3,
                            Day = 1,
                            Description = "Assist to English class"
                        });
                });

            modelBuilder.Entity("EastviewRestAPI.Models.CitizenTask", b =>
                {
                    b.HasOne("EastviewRestAPI.Models.Citizen", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
